# Base image
FROM    ubuntu:focal-20230301
# FROM    ubuntu:bionic-20230301

# Install essential CLI tools
RUN     apt-get update  &&\
        apt-get install wget curl nano vim fuse tree zip -y &&\
        apt-get clean

# Install Bash customization themes
RUN     wget -P /root/custom/themes https://raw.githubusercontent.com/sbp-dev/dockersetup/main/clean_detailed.omp.json &&\
        curl -s https://ohmyposh.dev/install.sh | bash -s &&\
        echo "\n########## Customization for Oh-My-Posh Bash themes ##########" >> ~/.bashrc &&\
        echo "eval \"\$(oh-my-posh init bash --config ~/custom/themes/clean_detailed.omp.json)\"" >> ~/.bashrc

# Set working directory
WORKDIR /workspace

# Anaconda installation and initialization
RUN     wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  &&\
        chmod 755 Miniconda3-latest-Linux-x86_64.sh &&\
        ./Miniconda3-latest-Linux-x86_64.sh -b &&\
        rm Miniconda3-latest-Linux-x86_64.sh &&\
        ~/miniconda3/bin/conda init
        
ENV     CONDA_PREFIX="~/miniconda3" PATH=$CONDA_PREFIX/bin/:$PATH

# Some customization required fro TensorFlow conda installation
RUN     mkdir -p ${CONDA_PREFIX}/etc/conda/activate.d &&\
        echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CONDA_PREFIX}/lib/' > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
