# Base image
FROM    ubuntu:focal-20230301
# FROM    ubuntu:bionic-20230301

# Install essential CLI tools
RUN     apt-get update  &&\
        apt-get install wget curl nano vim fuse tree zip -y &&\
        apt-get clean

# Install Bash customization themes
RUN     wget -P /root/custom/themes https://raw.githubusercontent.com/sbp-dev/dockersetup/main/clean_detailed.omp.json &&\
        curl -s https://ohmyposh.dev/install.sh | bash -s &&\
        echo "\n########## Customization for Oh-My-Posh Bash themes ##########" >> ~/.bashrc &&\
        echo "eval \"\$(oh-my-posh init bash --config ~/custom/themes/clean_detailed.omp.json)\"" >> ~/.bashrc

# Set working directory
WORKDIR /workspace